profe.webui/Controllers/AdminController.cs
 using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using profe.webui.Data.Repositories;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Identity;
using profe.webui.Entities;
using profe.webui.Models;
using profe.webui.Data.Services;
using Microsoft.EntityFrameworkCore;
using profe.webui.Extensions;
using System.IO;
using Azure.Storage.Blobs;
using Microsoft.Win32.SafeHandles;
using profe.webui.Exceptions.ProductExceptions;

namespace profe.webui.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;

        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICartService _cartService;

        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;

        public AdminController(IProductRepository productRepository, ICategoryRepository categoryRepository, ICartService cartService,
                              UserManager<User>  userManager, RoleManager<IdentityRole> roleManager, ILogger<AdminController> logger)
		{
            _logger = logger;
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _userManager = userManager;
            _roleManager = roleManager;
		}

        //PRODUCT PAGES

        public IActionResult ProductList()
        {

            try
            {
                var adminProducts = new ProductListViewModel()
                {
                    Products = _productRepository.GetAll()
                };

                return View(adminProducts);
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Ürünler listelenirken beklenmeyen bir hata oluştu.");
                ModelState.AddModelError("", "Ürünler listelenirken beklenmeyen bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.");

            }
            return View();

        }

        [HttpGet]
        public IActionResult CreateProduct()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(ProductModel model, IFormFile file)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var entity = new Product()
                    {
                        productName = model.Name,
                        Price = model.Price,
                        Description = model.Description,
                        Stock = model.Stock,
                        //ImgUrl = model.ImgUrl,
                        IsApproved = model.IsApproved,
                    };




                    var extention = Path.GetExtension(file.FileName);
                    var randomName = string.Format($"{Guid.NewGuid()}{extention}");
                    entity.ImgUrl = randomName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", randomName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }


                    _productRepository.AddAsync(entity);

                    TempData.Put("message", new AlertMessage()
                    {
                        Title = "Create Product",
                        Message = $"{entity.productName} isimli ürün eklendi.",
                        AlertType = "success"

                    });

                    return RedirectToAction("ProductList");
                }
            }
            catch(ProductTitleMustNotBeSameException ex)
            {
                _logger.LogError("Aynı isimde başka bir ürün eklenmeye çalışıldı",ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Ürün oluşturma sırasında beklenmeyen bir hata oluştu.");
                ModelState.AddModelError("", "Ürün oluşturma işlemi sırasında bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.");
            }

            return View(model);

        }

        [HttpGet]
        public IActionResult EditProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productRepository.GetProductDetails((int)id);

            if (id == null)
            {
                return NotFound();
            }

            var model = new ProductModel()
            {
                ProductId = product.Id,
                Name = product.productName,
                Price = product.Price,
                Description = product.Description,
                //ImgUrl = product.ImgUrl,

                SelectedCategories = product.ProductCategories.Select(i => i.Category).ToList()
            };

            ViewBag.Categories = _categoryRepository.GetAll();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditProduct(ProductModel model, int[] categoryIds, IFormFile file)
        {
            try
            {


                if (ModelState.IsValid)
                {

                    var product = _productRepository.GetProductDetails(model.ProductId);

                    if (product == null)
                    {
                        return NotFound();
                    }

                    product.productName = model.Name;
                    product.Price = model.Price;
                    product.Description = model.Description;
                    product.Stock = model.Stock;
                    product.IsApproved = model.IsApproved;

                    if (file != null)
                    {
                        var extention = Path.GetExtension(file.FileName);
                        var randomName = string.Format($"{Guid.NewGuid()}{extention}");
                        product.ImgUrl = randomName;
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", randomName);
                        //eski projede wwwroot\\img şeklindeydi, öyle ur kısmında hata verdi

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }
                    }

                    _productRepository.Update(product, categoryIds);


                    TempData.Put("message", new AlertMessage()
                    {
                        Title = "Update Product",
                        Message = $"{model.Name} isimli ürün güncellendi.",
                        AlertType = "success"

                    });

                    return RedirectToAction("ProductList");

                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Ürün düzenleme sırasında beklenmeyen bir hata oluştu.");
                //kullanıcı tarayıcı üzerinden hangi alanları eksik girdiğini daha estekik görsün diyehata fırlatmadım
                //ModelState.AddModelError("", "Ürün düzenleme işlemi sırasında bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.");
                return View(model);

            }

            ViewBag.Categories = _categoryRepository.GetAll();
            //burada bir linq sorgusuyla boş selectedcategories çek, döngüyü null referenceden kurtar
            return View(model);

        }

        //[HttpPost]
        //public async IActionResult deleteproduct(int productId)
        //{

        //    Product product = await _productRepository.GetById(productId);

        //    if (product != null)
        //    {
        //        _productRepository.Delete(product);
        //    }


        //    TempData.Put("message", new AlertMessage()
        //    {
        //        Title = "Delet Product",
        //        Message = $"{product.productName} adlı ürün silindi.",
        //        AlertType = "danger"

        //    });


        //    return RedirectToAction("ProductList");
        //}

        [HttpPost]
        public async Task<IActionResult> deleteproduct(int productId)
        {
            try
            {
                Product product = await _productRepository.GetById(productId);

                if (product != null)
                {
                    _productRepository.Delete(product);
                }


                TempData.Put("message", new AlertMessage()
                {
                    Title = "Delet Product",
                    Message = $"{product.productName} adlı ürün silindi.",
                    AlertType = "danger"

                });


                return RedirectToAction("ProductList");
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Ürün silme sırasında beklenmeyen bir hata oluştu.");
                ModelState.AddModelError("", "Ürün silme işlemi sırasında bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.");

            }
            return RedirectToAction("ProductList");


        }

        //USER PAGES
        public IActionResult UserCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserCreate(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new User()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                UserName = model.UserName,
                Email = model.Email,
                EmailConfirmed = true
            };



            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)

profe.webui/Controllers/CartController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using profe.webui.Data.Services;
using profe.webui.Entities;
using profe.webui.Models;

namespace profe.webui.Controllers
{
    public class CartController : Controller
    {
        private readonly ILogger<CartController> _logger;
        private readonly ICartService _cartService;
        private readonly UserManager<User> _userManager;
        public CartController(ICartService cartService, UserManager<User> userManager, ILogger<CartController> logger)
        {
            _logger = logger;
            _cartService = cartService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var model = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.productName,
                    Price = (double)i.Product.Price,
                    ImgUrl = i.Product.ImgUrl,
                    Quantity = i.Quantity
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.AddToCart(userId, productId, quantity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.DeleteFromCart(userId, productId);
            return RedirectToAction("Index");
        }
    }
}

profe.webui/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using profe.webui.Data.Repositories;
using profe.webui.Entities;
using profe.webui.Models;

namespace profe.webui.Controllers;

public class HomeController : Controller
{
    private readonly IProductRepository  _repository;
    private readonly IGenericRepository<Product> _genericRepository;
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger, IProductRepository repository, IGenericRepository<Product> genericRepository)
    {
        _logger = logger;
        _repository = repository;
        _genericRepository = genericRepository;
    }

    public IActionResult Index()
    {
        //Listeleme için kullan
        return View();
    }


    public IActionResult list(int? id, string q)
    {
        //include ile category ve subcategory bilgilerini çek


        if (id != null) 
        {
            var model = new ProductListViewModel()
            {
                Products =_repository.GetProductByCategoryId((int)id)
            };

            return View(model);
        }
        else if (!string.IsNullOrEmpty(q))
        {
            var model = new ProductListViewModel()
            {
                Products =  _repository.GetProductsByQSearch(q)
            };
            return View(model);
        }
        else
        {
            var model = new ProductListViewModel()
            {
                Products = _genericRepository.GetAll()
            };
            return View(model);
        }
    }

    public  IActionResult detail(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        Product product =  _repository.GetProductDetails((int)id);

        if (product == null)
        {
            return NotFound();
        }

        var model = new ProductDetailModel
        {
            Product = product,
            Categories = product.ProductCategories.Select(i => i.Category).ToList()
        };

        return View(model);
    }





    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

profe.webui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a asp-area="" asp-controller="Home" asp-action="list" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">ALL PRODUCTS</a>
</div>
<br />

<div class="text-center">
    @if (User.Identity.IsAuthenticated)
    {

        <a asp-area="" asp-controller="Admin" asp-action="rolelist" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Role List</a>

        <a asp-area="" asp-controller="Admin" asp-action="UserList" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">User List</a>

        <a asp-area="" asp-controller="Admin" asp-action="ProductList" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Product List</a>

    }
    else
    {
        <a asp-area="" asp-controller="Account" asp-action="register" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Register</a>

        <a asp-area="" asp-controller="Account" asp-action="login" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Login</a>
    }


    <a asp-area="" asp-controller="Account" asp-action="forgotpassword" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Reset Password</a>

</div>

profe.webui/Views/Home/List.cshtml
   @model profe.webui.Models.ProductListViewModel
<div class="row">
    <div class="col-md-2">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-10">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-md-3">
                    @await Html.PartialAsync("~/Views/Shared/_productCard.cshtml", product)
                </div>
            }
        </div>
    </div>
</div>

profe.webui/Views/Home/detail.cshtml
@model profe.webui.Models.ProductDetailModel

<div class="row">


    <div class="col-md-9">
        @* <div class="card mb-3"> *@
        <div class="card-body">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="~/img/@Model.Product.ImgUrl" class="card-img" style="box-shadow: 3px 3px 5px  #888888;">
                </div>
                <div class="col-md-9">

                    <h5 class="card-title">@Model.Product.productName.</h5>

                    @foreach (var item in Model.Categories)
                    {
                        <a href="/home/list/@item.Id" class="btn btn-link -0 mb-3"> @item.categoryName </a>
                    }
                    <p class="card-text">@Html.Raw(Model.Product.Description)</p>

                    <div class="mb-3">
                        <h4 class="text-secondary mb-3">
                            <i class="fa fa-turkish-lira">@Model.Product.Price</i>
                        </h4>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <form asp-controller="Cart" asp-action="AddToCart" method="POST" class="form-inline">
                                <input type="hidden" name="productId" value="@Model.Product.Id">
                                <div class="input-group mb-3">
                                    <div class="row" style="margin-right: 20px;">
                                        <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width: 100px;">
                                    </div>
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-secondary">
                                            <i class="fas fa-cart-plus"></i> Karta Ekle
                                        </button>
                                    </div>
                                </div>
                            </form>
                        }


                    </div>


                </div>
            </div>
        </div>



        @* </div> *@
    </div>
</div>